### ISSUE TITLE
Thanks and small note

### ISSUE THREAD

**Issue by TonyGravagno** [jsakamoto/CommandLineSwitchParser#1]
I just looked in NuGet for exactly this kind of function to abstract out the complications of a simple function like Options parsing. Thank you VERY much for making this elegant package available.

In your Readme example, you have a field Recuruce. That' not an English word. Just for example purposes, you might want to use RedirectOK, to indicate it's OK to follow a 302 redirect, or Recursive to indicate a request for that one web page will also retrieve all linked resources for that page.

I will use this package and report issues or other anomalies. I hope to see this as a v1.0 production soon. :)

ありがと!

**Comment by jsakamoto** [comment]
@TonyGravagno Thank you for your comment and advice. 👍 

I'm going to fix README.md according to your advice in these days.

And, I have to re-planning about release v.1.0 as soon as possible :)

**Comment by jsakamoto** [comment]
@TonyGravagno 
>  I hope to see this as a v1.0 production soon. :)

I did it.

[![image](https://user-images.githubusercontent.com/95908/30970533-5f0aa43c-a4a0-11e7-8f7e-719eaf73f633.png)](https://twitter.com/jsakamoto/status/913395394188500992)
