### ISSUE TITLE
typo in the home page sample usage

### ISSUE THREAD

**Issue by prasadbcs** [jsakamoto/CommandLineSwitchParser#5]
What you should do is only define your option class and write code like "var option = CommandLine**Swicth.**Parse<YourOptionClass>(ref args);".

should be
var option = CommandLineSwitch.Parse<YourOptionClass>(ref args);

**Comment by jsakamoto** [comment]
@prasadbcs Thank you for your report. 👍 

I fixed it.

https://github.com/jsakamoto/CommandLineSwitchParser/commit/7dfd5254a52fc7e34b8f5b6899ac240843d6a4ea

Thanks!
